FROM golang:latest

RUN mkdir /app
WORKDIR /app

RUN go get -u github.com/gin-gonic/gin
RUN go get -u github.com/go-sql-driver/mysql
RUN go get -u gorm.io/gorm
RUN go get -u gorm.io/driver/mysql
RUN go get github.com/gin-contrib/cors