version: '3.9'
services:
  hardhat:
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    restart: always
    command: yarn run dev
    volumes: 
      - ./hardhat:/app
      - /app/node_modules
      # - ./<PATH_TO_FRONTEND_DIR>/contracts:/app/tmp/contracts
    ports:
      - 8545:8545
  go:
    build: 
      context: .
      dockerfile: DockerFile
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - db
      - hardhat
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
volumes:
  db-data:
    driver: local